### ISSUE TITLE
inline coding

### ISSUE THREAD

**Issue by rileyesther** [RobbyRisse/the-startup-responsive-interactieve-website#1]
https://github.com/RobbyRisse/the-startup-responsive-interactieve-website/blob/dc130fe7d3f8e4a5e1e6eb9960607ea7784f5477/startup-backbase/startup.html#L28C5-L28C5

Probeer al gelijk in Java.script te coderen , op deze manier hoef je later niet terug om alles in java.script te zetten en blijft je code georganiseerd .

**Comment by RobbyRisse** [comment]
thanks Riley, heb het aangepast
